swiftmailer:
    transport: '%env(SWIFTMAILER_TRANSPORT)%'
    username: '%env(SWIFTMAILER_USERNAME)%'
    password: '%env(SWIFTMAILER_PASSWORD)%'
    host: '%env(SWIFTMAILER_HOST)%'
    port: '%env(SWIFTMAILER_PORT)%'
