# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    tkid: '%env(APP_SECRET)%'
    uploaded_directory:
        avatar: '%kernel.project_dir%/public/uploaded/avatar'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Service\PasswordEncoder:
        arguments:
            $cost: 12

    App\Service\CRM\IFTZohoClient:
        arguments:
            $url: '%env(ZOHO_URL)%'
            $authToken: '%env(ZOHO_AUTHTOKEN)%'
            $timeout: 5
            $uploadedDir: '%uploaded_directory%'

    App\Service\Auth:
            arguments:
                $admin_info:
                    login: ipopravka@hotmail.com
                    password: $2y$12$MhItjnKBoYezhw/CJi/6Yu32wi/zuwU7NbNm.TFuob0o6t1tkMNea
